name: VIII_Deployment CI

on:
  workflow_dispatch: 
  push:
    branches: [main]
   # paths: 'VIII_Deployment/**'
  pull_request:
    branches: [main]
   # paths: 'VIII_Deployment/**'
    
jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: VIII_Deployment
        run: npm install

      - name: Run tests and generate coverage
        working-directory: VIII_Deployment
        run: npm run coverage

      - name: Send coverage to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: npm run coveralls
